import cavalryIcon from '../assets/icons/warriors/cavalry.svg'
import elfIcon from '../assets/icons/warriors/elf.svg'
import footmanIcon from '../assets/icons/warriors/footman.svg'
import orcLightIcon from '../assets/icons/warriors/orc_light.svg'
import orcHeavyIcon from '../assets/icons/warriors/orc_heavy.svg'
import sorcererIcon from '../assets/icons/warriors/sorcerer.svg'

export const warriorsData = [
    {
        type: "Footman",
        name: "Пехотинец",
        race: 'human',
        army: 1,
        icon: footmanIcon,
        accuracy: 10,
        armor: 20,
        speed: 10,
        strength: 8,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Cavalry",
        name: "Всадник",
        race: 'human',
        army: 1,
        icon: cavalryIcon,
        accuracy: 10,
        armor: 13,
        speed: 15,
        strength: 15,
        quantity: 0,
        isAllow: true,
    },
    {
        name: "Эльф",
        race: 'elf',
        army: 1,
        icon: elfIcon,
        accuracy: 20,
        armor: 10,
        speed: 10,
        strength: 10,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Light",
        name: "Легкий Орк",
        race: 'orc',
        army: 1,
        icon: orcLightIcon,
        accuracy: 10,
        armor: 7,
        speed: 16,
        strength: 10,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Heavy",
        name: "Тяжелый Орк",
        race: 'orc',
        army: 1,
        icon: orcHeavyIcon,
        accuracy: 5,
        armor: 20,
        speed: 5,
        strength: 20,
        quantity: 0,
        isAllow: true,
    },
    {
        name: "Чародей",
        race: 'sorcerer',
        army: 1,
        icon: sorcererIcon,
        accuracy: 10,
        armor: 10,
        speed: 10,
        strength: 10,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Footman",
        name: "Пехотинец",
        race: 'human',
        army: 2,
        icon: footmanIcon,
        accuracy: 10,
        armor: 20,
        speed: 10,
        strength: 8,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Cavalry",
        name: "Всадник",
        race: 'human',
        army: 2,
        icon: cavalryIcon,
        accuracy: 10,
        armor: 13,
        speed: 15,
        strength: 15,
        quantity: 0,
        isAllow: true,
    },
    {
        name: "Эльф",
        race: 'elf',
        army: 2,
        icon: elfIcon,
        accuracy: 20,
        armor: 10,
        speed: 10,
        strength: 10,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Light",
        name: "Легкий Орк",
        race: 'orc',
        army: 2,
        icon: orcLightIcon,
        accuracy: 10,
        armor: 7,
        speed: 16,
        strength: 10,
        quantity: 0,
        isAllow: true,
    },
    {
        type: "Heavy",
        name: "Тяжелый Орк",
        race: 'orc',
        army: 2,
        icon: orcHeavyIcon,
        accuracy: 5,
        armor: 20,
        speed: 5,
        strength: 20,
        quantity: 0,
        isAllow: true,
    },
    {
        name: "Чародей",
        race: 'sorcerer',
        army: 2,
        icon: sorcererIcon,
        accuracy: 10,
        armor: 0,
        speed: 10,
        strength: 0,
        quantity: 0,
        isAllow: true,
    },
]

export const nameMapping = {
    "Легкий орк": { genitive: "Легкого орка", dative: "Легкому орку" },
    "Чародей": { genitive: "Чародея", dative: "Чародею" },
    "Тяжелый орк": { genitive: "Тяжелого орка", dative: "Тяжелому орку" },
    "Пехотинец": { genitive: "Пехотинца", dative: "Пехотинцу" },
    "Кавалерист": { genitive: "Кавалериста", dative: "Кавалеристу" },
    "Эльф": { genitive: "Эльфа", dative: "Эльфу" },
};